spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #公司电脑
#    url: jdbc:mysql://192.168.13.163/sell?characterEncoding=utf-8&useSSL=false
    #自己电脑
    url: jdbc:mysql://192.168.0.112/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    
server:
  context-path: /sell